### ISSUE TITLE
trained model not existing

### ISSUE THREAD

**Issue by GiulioBen** [sensynehealth/lung-ct-covid-pathology-detection#1]
Thank you for this build.

I was going to check if it is working on my data but the trained model (i.e. https://github.com/draysontechnologies/lung-ct-covid-pathology-detection/releases/download/v0.1/unet_covid_crossval_200.hdf5) is not present.

Could you provide a working link?

Thank you.

**Comment by benjaminirving** [comment]
Thanks for flagging @GiulioBen. I'll re-add the link today and update

**Comment by benjaminirving** [comment]
Thanks again. The link should now work.
